version: "3"
services:
  code:
    image: aymericbernard/rerum-imperium:latest
    container_name: cn_rerum_imperium
    restart: always
#    networks:
#      - proxy
    ports:
      - "4200:80"
#    environment:
#      - VIRTUAL_HOST=rerum-imperium.kyr.pw
#      - LETSENCRYPT_HOST=rerum-imperium.kyr.pw
#      - LETSENCRYPT_EMAIL=nope@example.com
#      - APP_SHORT_NAME=Rerum
#      - NGX_backendUrl="https://rerum-imperium-backend.example.com"
#      - NGX_websiteUrl="https://rerum-imperium.example.com"
#networks:
#  proxy:
#    external:
#      name: nginx-proxy
